# 방향
- 이중분류 할것이다: 사진이 주어졌을때 이게 개냐 ~ 아니냐 ~

# 할거
- 3개의 함수 : 학습, 검증 및 테스트, 예측
- 모델 : 층, 층별 노드, 퍼셉트론 수 조절한게 있어야 함

In [2]:
from PIL import Image
import numpy as np
import pandas as pd
# from sklearn.datasets import fetch_openml 
# from sklearn.preprocessing import LabelEncoder, OneHotEncoder
# import torch
# import torch.nn.functional as F 
# import torch.nn as nn 
# from torch.utils.data import Dataset, DataLoader, random_split
# import torch.optim as optim 
# import torchmetrics.functional as metrics

In [15]:
# 회색으로 변환 후 이미지 파일 불러오기
# img = Image.open('C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/animal_faces/train/cat/pixabay_cat_000002.jpg').convert('L')
# pix = np.array(img)
# print(img.size)
# x = np.array(img)
# print(x)
# print(x.shape)

# 회색으로 변환 => 사진 픽셀 수 변경 (30, 30) => 이미지 저장 => 저장된 이미지 파일 불러오기

In [6]:
i = 2
img = Image.open(f'C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/animal_faces/train/cat/pixabay_cat_00000{i}.jpg').convert('L')
print(f"before size : {img.size}")
img_resize = img.resize((30, 30))
print(f"after size : {img_resize.size}")
img_resize.save(f'cat_img_{i}.jpg')

pix = np.array(img_resize)
x = np.array(img_resize)
print(x)
print(x.shape)

before size : (512, 512)
after size : (30, 30)
[[149 107  79 140 146 174 175 132 110 107  94  74  59  48  52  62  77  77
   88  96 117 123 118 110 141 114  97  50  77 103]
 [150 126 117 163 163 193 180 170 117  83  73  63  34  28  38  41  43  49
   84  95 101 104 153 155 144 107  91  72  81 106]
 [150 142 135 167 174 197 189 170 161  78  43  45  31  38  52  41  33  32
   71  67  93 149 156 145 141 125 107  87  87 111]
 [145 140 126 167 169 196 192 178 168 116  34  23  41  58  28  36  36  42
   67  68 143 150 156 168 174 144 114  86  93 117]
 [140 142 136 177 197 164 158 146 155 124  47  45  80  52  20  34  48  71
   53 107 131 145 145 169 165 114 114 103  99 121]
 [142 143 142 197 167 128 114 130 126 117  64  66  76  40  39  65  77  54
   59 121  94 101 120 128 129 126 133 120 104 124]
 [143 134 156 203 162 122 125 139  94 102  59  57  59  40  52  82  51  43
   60  78 108 157 132  83  77  90 138 132 113 126]
 [139 129 164 190 183 186 187 153  93  75  26  61  89  37  60  73  66  14
   4

In [7]:
no_file_num = []
for i in range(2, 10):
    try:
        img = Image.open(f'C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/animal_faces/train/cat/pixabay_cat_00000{i}.jpg').convert('L')
        
        img_resize = img.resize((30, 30))
        img_resize.save(f'cat_img_{i}.jpg')
        
        pix = np.array(img_resize)
        x = np.array(img_resize)
        # print(f"{i}번 이미지 shape => {x.shape}")
    except:
        print(f'예외 발생! => {i}번 이미지 없음')
        no_file_num.append(i)

예외 발생! => 7번 이미지 없음


In [8]:
for i in range(10, 100):
    try:
        img = Image.open(f'C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/animal_faces/train/cat/pixabay_cat_0000{i}.jpg').convert('L')
        
        img_resize = img.resize((30, 30))
        img_resize.save(f'cat_img_{i}.jpg')
        
        pix = np.array(img_resize)
        x = np.array(img_resize)
        # print(f"{i}번 이미지 shape => {x.shape}")
    except:
        print(f'예외 발생! => {i}번 이미지 없음')
        no_file_num.append(i)

예외 발생! => 10번 이미지 없음
예외 발생! => 37번 이미지 없음
예외 발생! => 40번 이미지 없음
예외 발생! => 51번 이미지 없음
예외 발생! => 70번 이미지 없음
예외 발생! => 76번 이미지 없음
예외 발생! => 81번 이미지 없음
예외 발생! => 96번 이미지 없음
예외 발생! => 99번 이미지 없음


In [11]:
for i in range(100, 501):
    try:
        img = Image.open(f'C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/animal_faces/train/cat/pixabay_cat_000{i}.jpg').convert('L')
        
        img_resize = img.resize((30, 30))
        img_resize.save(f'cat_img_{i}.jpg')
        
        pix = np.array(img_resize)
        x = np.array(img_resize)
        # print(f"{i}번 이미지 shape => {x.shape}")
    except:
        print(f'예외 발생! => {i}번 이미지 없음')
        no_file_num.append(i)

예외 발생! => 108번 이미지 없음
예외 발생! => 117번 이미지 없음
예외 발생! => 126번 이미지 없음
예외 발생! => 147번 이미지 없음
예외 발생! => 151번 이미지 없음
예외 발생! => 165번 이미지 없음
예외 발생! => 169번 이미지 없음
예외 발생! => 178번 이미지 없음
예외 발생! => 181번 이미지 없음
예외 발생! => 190번 이미지 없음
예외 발생! => 202번 이미지 없음
예외 발생! => 231번 이미지 없음
예외 발생! => 241번 이미지 없음
예외 발생! => 248번 이미지 없음
예외 발생! => 276번 이미지 없음
예외 발생! => 291번 이미지 없음
예외 발생! => 296번 이미지 없음
예외 발생! => 299번 이미지 없음
예외 발생! => 302번 이미지 없음
예외 발생! => 314번 이미지 없음
예외 발생! => 315번 이미지 없음
예외 발생! => 325번 이미지 없음
예외 발생! => 339번 이미지 없음
예외 발생! => 343번 이미지 없음
예외 발생! => 353번 이미지 없음
예외 발생! => 355번 이미지 없음
예외 발생! => 380번 이미지 없음
예외 발생! => 390번 이미지 없음
예외 발생! => 392번 이미지 없음
예외 발생! => 403번 이미지 없음
예외 발생! => 417번 이미지 없음
예외 발생! => 440번 이미지 없음
예외 발생! => 441번 이미지 없음
예외 발생! => 459번 이미지 없음
예외 발생! => 468번 이미지 없음
예외 발생! => 491번 이미지 없음
예외 발생! => 492번 이미지 없음


In [5]:
# print(len(no_file_num))

In [6]:
img = Image.open('C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/animal_faces/train/cat/pixabay_cat_000002.jpg').convert('L')
pix = np.array(img)
x = np.array(img)
print(x.shape)
print(x)

(512, 512)
[[165 163 161 ... 104 104 104]
 [165 163 161 ... 104 104 104]
 [165 163 161 ... 104 104 104]
 ...
 [158 157 157 ...  91  90  90]
 [156 155 155 ...  92  92  92]
 [155 154 155 ...  93  93  93]]


# dataframe으로 만들기 위해 각 픽셀 값을 담은 리스트 생성

In [12]:
total_list = []   # 모든 이미지 파일들의 픽셀값을 담은 리스트를 모두 담은 리스트
list = []  # 1개의 이미지 파일에 대한 픽셀값
count = 1
for first in range(len(x)):
    # print(f"----- {count} ------")
    # print(x[first])
    # count +=1
    for value in range(len(x[first])):
        list.append(x[first][value])

In [13]:
total_list = []   # 모든 이미지 파일들의 픽셀값을 담은 리스트를 모두 담은 리스트
# no_file_num
for i in range(2, 501):
    if i not in no_file_num:
        img = Image.open(f'C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/resize_image/cat_img_{i}.jpg').convert('L')
        pix = np.array(img)
        x = np.array(img)

        list = []  # 1개의 이미지 파일에 대한 픽셀값
        for first in range(len(x)):
            for value in range(len(x[first])):
                list.append(x[first][value])
        total_list.append(list)
        
print(len(total_list))

452


In [17]:
# for i in range(100, 113):
#     if i not in no_file_num:
#         img = Image.open(f'C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/animal_faces/train/cat/pixabay_cat_000{i}.jpg').convert('L')
#         pix = np.array(img)
#         x = np.array(img)
# 
#         list = []  # 1개의 이미지 파일에 대한 픽셀값
#         for first in range(len(x)):
#             for value in range(len(x[first])):
#                 list.append(x[first][value])
#         total_list.append(list)
# print(len(total_list))

# 데이터 프레임 생성 => csv 파일로 저장

In [15]:
cat_df = pd.DataFrame(total_list)
cat_df.to_csv('resize_cat_df.csv')

In [9]:
col_list = []
for i in range(1,262145):
    col_list.append(f"pixel{i}")
    
print(col_list[-5:])

['pixel262140', 'pixel262141', 'pixel262142', 'pixel262143', 'pixel262144']


In [ ]:
# cat_df.to_csv('cat_df.csv')