# 방향
- 이중분류 할것이다: 사진이 주어졌을때 이게 개냐 ~ 아니냐 ~

# 할거
- 3개의 함수 : 학습, 검증 및 테스트, 예측
- 모델 : 층, 층별 노드, 퍼셉트론 수 조절한게 있어야 함

In [1]:
from PIL import Image
import numpy as np
import pandas as pd
# from sklearn.datasets import fetch_openml 
# from sklearn.preprocessing import LabelEncoder, OneHotEncoder
# import torch
# import torch.nn.functional as F 
# import torch.nn as nn 
# from torch.utils.data import Dataset, DataLoader, random_split
# import torch.optim as optim 
# import torchmetrics.functional as metrics

In [15]:
# 회색으로 변환 후 이미지 파일 불러오기
# img = Image.open('C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/animal_faces/train/cat/pixabay_cat_000002.jpg').convert('L')
# pix = np.array(img)
# print(img.size)
# x = np.array(img)
# print(x)
# print(x.shape)

In [2]:
no_file_num = []
for i in range(2, 10):
    try:
        img = Image.open(f'C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/animal_faces/train/cat/pixabay_cat_00000{i}.jpg').convert('L')
        pix = np.array(img)
        x = np.array(img)
        # print(f"{i}번 이미지 shape => {x.shape}")
    except:
        print(f'예외 발생! => {i}번 이미지 없음')
        no_file_num.append(i)

예외 발생! => 7번 이미지 없음


In [3]:
for i in range(10, 100):
    try:
        img = Image.open(f'C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/animal_faces/train/cat/pixabay_cat_0000{i}.jpg').convert('L')
        pix = np.array(img)
        x = np.array(img)
        # print(f"{i}번 이미지 shape => {x.shape}")
    except:
        print(f'예외 발생! => {i}번 이미지 없음')
        no_file_num.append(i)

예외 발생! => 10번 이미지 없음
예외 발생! => 37번 이미지 없음
예외 발생! => 40번 이미지 없음
예외 발생! => 51번 이미지 없음
예외 발생! => 70번 이미지 없음
예외 발생! => 76번 이미지 없음
예외 발생! => 81번 이미지 없음
예외 발생! => 96번 이미지 없음
예외 발생! => 99번 이미지 없음


In [4]:
for i in range(100, 1010):
    try:
        img = Image.open(f'C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/animal_faces/train/cat/pixabay_cat_000{i}.jpg').convert('L')
        pix = np.array(img)
        x = np.array(img)
        # print(f"{i}번 이미지 shape => {x.shape}")
    except:
        print(f'예외 발생! => {i}번 이미지 없음')
        no_file_num.append(i)

예외 발생! => 108번 이미지 없음
예외 발생! => 117번 이미지 없음
예외 발생! => 126번 이미지 없음
예외 발생! => 147번 이미지 없음
예외 발생! => 151번 이미지 없음
예외 발생! => 165번 이미지 없음
예외 발생! => 169번 이미지 없음
예외 발생! => 178번 이미지 없음
예외 발생! => 181번 이미지 없음
예외 발생! => 190번 이미지 없음
예외 발생! => 202번 이미지 없음
예외 발생! => 231번 이미지 없음
예외 발생! => 241번 이미지 없음
예외 발생! => 248번 이미지 없음
예외 발생! => 276번 이미지 없음
예외 발생! => 291번 이미지 없음
예외 발생! => 296번 이미지 없음
예외 발생! => 299번 이미지 없음
예외 발생! => 302번 이미지 없음
예외 발생! => 314번 이미지 없음
예외 발생! => 315번 이미지 없음
예외 발생! => 325번 이미지 없음
예외 발생! => 339번 이미지 없음
예외 발생! => 343번 이미지 없음
예외 발생! => 353번 이미지 없음
예외 발생! => 355번 이미지 없음
예외 발생! => 380번 이미지 없음
예외 발생! => 390번 이미지 없음
예외 발생! => 392번 이미지 없음
예외 발생! => 403번 이미지 없음
예외 발생! => 417번 이미지 없음
예외 발생! => 440번 이미지 없음
예외 발생! => 441번 이미지 없음
예외 발생! => 459번 이미지 없음
예외 발생! => 468번 이미지 없음
예외 발생! => 491번 이미지 없음
예외 발생! => 492번 이미지 없음
예외 발생! => 504번 이미지 없음
예외 발생! => 514번 이미지 없음
예외 발생! => 518번 이미지 없음
예외 발생! => 531번 이미지 없음
예외 발생! => 535번 이미지 없음
예외 발생! => 540번 이미지 없음
예외 발생! => 542번 이미지 없음
예외 발생! => 573번 이미지 없음
예외 발생! => 

In [5]:
# print(len(no_file_num))

In [6]:
img = Image.open('C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/animal_faces/train/cat/pixabay_cat_000002.jpg').convert('L')
pix = np.array(img)
x = np.array(img)
print(x.shape)
print(x)

(512, 512)
[[165 163 161 ... 104 104 104]
 [165 163 161 ... 104 104 104]
 [165 163 161 ... 104 104 104]
 ...
 [158 157 157 ...  91  90  90]
 [156 155 155 ...  92  92  92]
 [155 154 155 ...  93  93  93]]


In [7]:
total_list = []   # 모든 이미지 파일들의 픽셀값을 담은 리스트를 모두 담은 리스트
list = []  # 1개의 이미지 파일에 대한 픽셀값
count = 1
for first in range(len(x)):
    # print(f"----- {count} ------")
    # print(x[first])
    # count +=1
    for value in range(len(x[first])):
        list.append(x[first][value])

In [16]:
total_list = []   # 모든 이미지 파일들의 픽셀값을 담은 리스트를 모두 담은 리스트

# no_file_num
for i in range(2, 10):
    if i not in no_file_num:
        img = Image.open(f'C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/animal_faces/train/cat/pixabay_cat_00000{i}.jpg').convert('L')
        pix = np.array(img)
        x = np.array(img)

        list = []  # 1개의 이미지 파일에 대한 픽셀값
        for first in range(len(x)):
            for value in range(len(x[first])):
                list.append(x[first][value])
        total_list.append(list)

for i in range(10, 57):
    if i not in no_file_num:
        img = Image.open(f'C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/animal_faces/train/cat/pixabay_cat_0000{i}.jpg').convert('L')
        pix = np.array(img)
        x = np.array(img)

        list = []  # 1개의 이미지 파일에 대한 픽셀값
        for first in range(len(x)):
            for value in range(len(x[first])):
                list.append(x[first][value])
        total_list.append(list)
        
print(len(total_list))

50


In [17]:
# for i in range(100, 113):
#     if i not in no_file_num:
#         img = Image.open(f'C:/Users/kdp/PycharmProjects/EXAM_DL/KDT_09_DEEP_LEARNING/project/animal_faces/train/cat/pixabay_cat_000{i}.jpg').convert('L')
#         pix = np.array(img)
#         x = np.array(img)
# 
#         list = []  # 1개의 이미지 파일에 대한 픽셀값
#         for first in range(len(x)):
#             for value in range(len(x[first])):
#                 list.append(x[first][value])
#         total_list.append(list)
# print(len(total_list))

In [19]:
cat_df = pd.DataFrame(total_list)
cat_df.to_csv('cat_df.csv')

In [9]:
col_list = []
for i in range(1,262145):
    col_list.append(f"pixel{i}")
    
print(col_list[-5:])

['pixel262140', 'pixel262141', 'pixel262142', 'pixel262143', 'pixel262144']


In [ ]:
# cat_df.to_csv('cat_df.csv')